global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: prometheus-dev-eu-west-1
    aws_environment: dev
    replica: 0

scrape_configs:
  - job_name: 'prometheus-dev'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'prometheus-a-dev-ec2-instance.mydomain.com'
